---
title: "Simple Linear Regresssion"
author: "Viplove Bandhe"
date: "11 March 2018"
output: html_document
---

```{r}
dataset = read.csv("file:///E:/Machine Learning Udemy/Machine Learning A-Z/Part 2 - Regression/Section 4 - Simple Linear Regression/Salary_Data.csv")
```


# splitting the data into training and test set
```{r}
library(caTools)
set.seed(123)
split = sample.split(dataset$Salary, SplitRatio = 2/3)
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)
```

# Simple Linear Regression
```{r}
regressor = lm(formula = Salary ~ YearsExperience,
               data = training_set)
summary(regressor)
```

# Predicting the test results
```{r}
y_pred = predict(regressor, newdata = test_set)
```

# Visualising the training set results
```{r}
library(ggplot2)
ggplot() + 
  geom_point(aes(x = training_set$YearsExperience, y = training_set$Salary),
             color = 'blue') + 
  geom_line(aes(x = training_set$YearsExperience, y = predict(regressor, newdata = training_set))
            ,color = 'red') + 
  ggtitle('Salary vs YearsofExperience(Training set)') + 
  xlab('Years of experience') + 
  ylab('Salary')
```

# Visualising the test set results
```{r}
library(ggplot2)
ggplot() + 
  geom_point(aes(x = test_set$YearsExperience, y = test_set$Salary),
             color = 'blue') + 
  geom_line(aes(x = training_set$YearsExperience, y = predict(regressor, newdata = training_set))
            ,color = 'red') + 
  ggtitle('Salary vs YearsofExperience(Test set)') + 
  xlab('Years of experience') + 
  ylab('Salary')
```

# Feature Scaling
```{r}
training_set[, 2:3] = scale(training_set[, 2:3])
test_set[, 2:3] = scale(test_set[, 2:3])
```


